version: '3'
services:
  vf-kb-scrapper-uploader:
    build: .
    restart: unless-stopped
    image: 'vf-kb-scrapper-uploader'
    container_name: 'vf-kb-scrapper-uploader'
    ports:
      - '${PORT}:${PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
  scrapper:
    image: 'amerkurev/scrapper:latest'
    restart: unless-stopped
    container_name: 'scrapper'
